/*
 * Course player: navigation, progress tracking, quizzes and summary.
 * Content comes from js/course-data.js (generated by scripts/build.py from
 * content/course.json). UI strings are Spanish on purpose: learners see them.
 */
(function () {
  "use strict";

  var COURSE = window.COURSE;
  var IMAGES = window.COURSE_IMAGES || {};
  var SCORM = window.SCORM;
  var units = COURSE.units;

  // ------------------------------------------------------------------ state
  var state = {
    seen: {},      // unitId -> [bool per slide]
    quiz: {},      // unitId -> {best: 0-100, tries: n}
    cert: null,    // issued certificate {serial, issued (YYYY-MM-DD), grade, name, sha256, md5}
    certHistory: [], // earlier certificates (grade changed), newest first, max 10
    view: { unit: 0, slide: 0, mode: "slide" } // mode: slide | quiz | summary
  };
  var quizRun = null; // in-memory state of the quiz being answered

  units.forEach(function (u) {
    state.seen[u.id] = u.slides.map(function () { return false; });
  });

  function passingScore() {
    var m = SCORM.masteryScore();
    return m != null ? m : COURSE.passingScore;
  }

  // Progress is keyed by lesson/unit ids (not positions) so lessons can be
  // added or reordered without scrambling what learners already saved.
  function serialize() {
    var seen = [];
    units.forEach(function (u) {
      u.slides.forEach(function (s, i) { if (state.seen[u.id][i]) seen.push(s.id); });
    });
    var q = {};
    Object.keys(state.quiz).forEach(function (k) { q[k] = [state.quiz[k].best, state.quiz[k].tries]; });
    var out = { v: 3, s: seen, q: q };
    if (state.cert) out.c = state.cert;
    if (state.certHistory.length) out.h = state.certHistory;
    return JSON.stringify(out);
  }

  function restore(raw) {
    if (!raw) return;
    try {
      var d = JSON.parse(raw);
      var seen = {};
      (Array.isArray(d.s) ? d.s : []).forEach(function (id) { seen[id] = true; });
      units.forEach(function (u) {
        state.seen[u.id] = u.slides.map(function (s) { return !!seen[s.id]; });
      });
      if (d.q) Object.keys(d.q).forEach(function (k) {
        state.quiz[k] = { best: d.q[k][0] || 0, tries: d.q[k][1] || 0 };
      });
      if (d.c && d.c.serial) state.cert = d.c;
      if (Array.isArray(d.h)) state.certHistory = d.h.filter(function (c) { return c && c.serial; }).slice(0, 10);
    } catch (e) { /* corrupt data: start fresh */ }
  }

  function locationString() {
    var v = state.view;
    if (v.mode === "summary") return "summary";
    return v.mode === "quiz" ? units[v.unit].id + ":quiz" : units[v.unit].slides[v.slide].id;
  }

  function restoreLocation(loc) {
    if (!loc) return;
    if (loc === "summary") { state.view = { unit: units.length - 1, slide: 0, mode: "summary" }; return; }
    units.forEach(function (u, ui) {
      if (loc === u.id + ":quiz") state.view = { unit: ui, slide: 0, mode: "quiz" };
      u.slides.forEach(function (s, si) {
        if (s.id === loc) state.view = { unit: ui, slide: si, mode: "slide" };
      });
    });
  }

  // ------------------------------------------------------------- progress
  function stats() {
    var totalSlides = 0, seenSlides = 0, attempted = 0, sum = 0, passedUnits = 0;
    var pass = passingScore();
    units.forEach(function (u) {
      totalSlides += u.slides.length;
      seenSlides += state.seen[u.id].filter(Boolean).length;
      var q = state.quiz[u.id];
      if (q && q.tries > 0) { attempted++; sum += q.best; if (q.best >= pass) passedUnits++; }
    });
    var average = Math.round(sum / units.length);
    var weightQuiz = 3;
    var percent = Math.round(100 * (seenSlides + weightQuiz * attempted) /
                             (totalSlides + weightQuiz * units.length));
    var allSeen = seenSlides === totalSlides;
    var allAttempted = attempted === units.length;
    return {
      totalSlides: totalSlides, seenSlides: seenSlides, attempted: attempted,
      average: average, percent: percent, passedUnits: passedUnits,
      complete: allSeen && allAttempted, passed: allSeen && allAttempted && average >= pass
    };
  }

  function unitDone(u) {
    var q = state.quiz[u.id];
    return state.seen[u.id].every(Boolean) && q && q.best >= passingScore();
  }

  function saveProgress() {
    var st = stats();
    SCORM.set("cmi.suspend_data", serialize());
    SCORM.set("cmi.core.lesson_location", locationString());
    if (st.attempted > 0) {
      SCORM.set("cmi.core.score.min", "0");
      SCORM.set("cmi.core.score.max", "100");
      SCORM.set("cmi.core.score.raw", String(st.average));
    }
    SCORM.set("cmi.core.lesson_status", st.complete ? (st.passed ? "passed" : "failed") : "incomplete");
    SCORM.commit();
  }

  // ---------------------------------------------------------------- markup
  function esc(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  function keys(combo) {
    return combo.split("+").map(function (k) { return "<kbd>" + k.trim() + "</kbd>"; }).join("<span class=\"plus\">+</span>");
  }

  function menuPath(path) {
    return "<span class=\"menu-path\">" + path.split("▸").map(function (p) {
      return "<span>" + p.trim() + "</span>";
    }).join("<span class=\"sep\" aria-hidden=\"true\">▸</span>") + "</span>";
  }

  // Inline markup: **bold**, `code`, [[Menú ▸ Ítem]], {{Ctrl+G}}
  function md(text) {
    var codes = [];
    var out = esc(text).replace(/`([^`]+)`/g, function (_, c) {
      codes.push("<code>" + c + "</code>");
      return "\u0000" + (codes.length - 1) + "\u0000";
    });
    out = out
      .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
      .replace(/\[\[([^\]]+)\]\]/g, function (_, p) { return menuPath(p); })
      .replace(/\{\{([^}]+)\}\}/g, function (_, k) { return keys(k); });
    return out.replace(/\u0000(\d+)\u0000/g, function (_, i) { return codes[+i]; });
  }

  // ---------------------------------------------------------------- icons
  var ICONS = {
    flag: "M5 21V4m0 0h11l-2 4 2 4H5",
    book: "M4 5a2 2 0 0 1 2-2h13v16H6a2 2 0 0 0-2 2V5Zm0 16a2 2 0 0 1 2-2h13",
    calculator: "M6 3h12a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Zm2 3h8v3H8V6Zm0 6h.01M12 12h.01M16 12h.01M8 16h.01M12 16h.01M16 16h.01",
    chart: "M4 20h16M7 16v-5M12 16V6M17 16v-8",
    broom: "M14 4l6 6M12 6l6 6-5 5-8 1 1-8 6-4Zm-4 9 3 3",
    check: "M5 12.5l4.5 4.5L19 7.5",
    menu: "M4 7h16M4 12h16M4 17h16",
    close: "M6 6l12 12M18 6 6 18",
    left: "M15 5l-7 7 7 7",
    right: "M9 5l7 7-7 7",
    download: "M12 4v11m0 0-4-4m4 4 4-4M5 20h14",
    zoom: "M10.5 17a6.5 6.5 0 1 0 0-13 6.5 6.5 0 0 0 0 13Zm4.7-1.8L20 20M10.5 8v5M8 10.5h5",
    trophy: "M8 4h8v5a4 4 0 0 1-8 0V4Zm0 2H5a3 3 0 0 0 3 4m8-4h3a3 3 0 0 1-3 4m-4 3v4m-4 3h8",
    quiz: "M9 9a3 3 0 1 1 4 2.8c-.6.3-1 .8-1 1.5V14m0 3h.01M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Z",
    tip: "M9 18h6m-5 3h4M12 3a6 6 0 0 0-3.5 10.9c.4.3.5.7.5 1.1v1h6v-1c0-.4.2-.8.5-1.1A6 6 0 0 0 12 3Z",
    warn: "M12 9v4m0 3h.01M10.3 4.3 2.6 18a2 2 0 0 0 1.7 3h15.4a2 2 0 0 0 1.7-3L13.7 4.3a2 2 0 0 0-3.4 0Z",
    note: "M12 11v5m0-8h.01M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Z",
    copy: "M9 9h10v11H9zM5 15V4h10",
    progress: "M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm0-9V7m0 5 3 3"
  };

  function icon(name, cls) {
    return "<svg class=\"icon " + (cls || "") + "\" viewBox=\"0 0 24 24\" aria-hidden=\"true\" focusable=\"false\">" +
      "<path d=\"" + (ICONS[name] || ICONS.note) + "\"/></svg>";
  }

  // --------------------------------------------------------------- images
  function imgTag(src, alt, eager) {
    var meta = IMAGES[src];
    if (!meta) return "<div class=\"missing\">Imagen no encontrada: " + esc(src) + "</div>";
    var srcset = meta.widths.map(function (w) {
      return "multimedia/img/" + src + "-" + w + "." + meta.ext + " " + w + "w";
    }).join(", ");
    var fallback = "multimedia/img/" + src + "-" + meta.widths[0] + "." + meta.ext;
    return "<img src=\"" + fallback + "\" srcset=\"" + srcset + "\"" +
      " sizes=\"(min-width: 1180px) 820px, (min-width: 900px) calc(100vw - 380px), calc(100vw - 32px)\"" +
      " width=\"" + meta.w + "\" height=\"" + meta.h + "\" alt=\"" + esc(alt) + "\"" +
      (eager ? "" : " loading=\"lazy\"") + " decoding=\"async\">";
  }

  function figure(src, alt, caption, eager, extraClass) {
    var meta = IMAGES[src] || {};
    var shape = meta.w && meta.h / meta.w > 0.9 ? " tall" : "";
    return "<figure class=\"shot" + shape + (extraClass ? " " + extraClass : "") + "\">" +
      "<button type=\"button\" class=\"zoomable\"" +
      (meta.w ? " style=\"--r:" + (meta.w / meta.h).toFixed(4) + "\"" : "") + " data-zoom=\"" + esc(src) + "\" data-alt=\"" + esc(alt) + "\"" +
      " aria-label=\"Ampliar imagen: " + esc(alt) + "\">" + imgTag(src, alt, eager) +
      "<span class=\"zoom-hint\">" + icon("zoom") + "<span>Ampliar</span></span></button>" +
      (caption ? "<figcaption>" + md(caption) + "</figcaption>" : "") + "</figure>";
  }

  // --------------------------------------------------------------- blocks
  var CALLOUT_TITLES = { tip: "Consejo", warn: "Atención", note: "Dato útil" };

  function block(b) {
    switch (b.t) {
      case "p": return "<p>" + md(b.x) + "</p>";
      case "ul": return "<ul>" + b.items.map(function (i) { return "<li>" + md(i) + "</li>"; }).join("") + "</ul>";
      case "steps": return "<ol class=\"steps\">" + b.items.map(function (i) { return "<li>" + md(i) + "</li>"; }).join("") + "</ol>";
      case "legend": return "<ol class=\"legend\">" + b.items.map(function (i) { return "<li>" + md(i) + "</li>"; }).join("") + "</ol>";
      case "tip": case "warn": case "note":
        return "<aside class=\"callout " + b.t + "\">" + icon(b.t) + "<div><strong class=\"callout-title\">" +
          CALLOUT_TITLES[b.t] + "</strong>" + md(b.x) + "</div></aside>";
      case "code":
        return "<div class=\"code\"><div class=\"code-head\"><span>" + esc(b.label || "") + "</span>" +
          "<button type=\"button\" class=\"copy\" data-copy=\"" + esc(b.x) + "\">" + icon("copy") + "<span>Copiar</span></button></div>" +
          "<pre><code>" + esc(b.x) + "</code></pre></div>";
      case "table":
        return "<div class=\"table-wrap\"><table><thead><tr>" + b.head.map(function (h) { return "<th scope=\"col\">" + md(h) + "</th>"; }).join("") +
          "</tr></thead><tbody>" + b.rows.map(function (r) {
            return "<tr>" + r.map(function (c) { return "<td>" + md(c) + "</td>"; }).join("") + "</tr>";
          }).join("") + "</tbody></table></div>";
      case "img": return figure(b.src, b.alt, b.caption, false, "inline");
      case "download":
        return "<a class=\"download\" href=\"multimedia/practica/" + esc(b.file) + "\" download>" + icon("download") +
          "<span><strong>" + esc(b.label) + "</strong><span class=\"file\">" + esc(b.file) + "</span>" +
          "<span class=\"desc\">" + md(b.desc) + "</span></span></a>";
      default: return "";
    }
  }

  // ------------------------------------------------------------------- DOM
  var $ = function (id) { return document.getElementById(id); };
  var els = {};

  function renderNav() {
    var st = stats();
    els.progressBar.style.width = st.percent + "%";
    els.progressBar.parentNode.setAttribute("aria-valuenow", st.percent);
    els.progressText.textContent = st.percent + " % completado";
    els.scoreText.textContent = "Evaluaciones " + st.attempted + "/" + units.length;
    els.scoreNote.textContent = st.attempted ?
      "Nota acumulada: " + st.average + "/100 (promedio de las " + units.length + " unidades; se aprueba con " + passingScore() + ")" :
      "Tu nota aparecerá al presentar la primera evaluación.";
    els.mobileProgress.style.width = st.percent + "%";

    var html = units.map(function (u, ui) {
      var current = state.view.mode !== "summary" && state.view.unit === ui;
      var seen = state.seen[u.id].filter(Boolean).length;
      var q = state.quiz[u.id];
      var done = unitDone(u);
      var status = done ? icon("check", "status done") :
        "<span class=\"status count\">" + seen + "/" + u.slides.length + "</span>";
      var inner = "";
      if (current) {
        inner = "<ol class=\"lessons\">" + u.slides.map(function (s, si) {
          var active = state.view.mode === "slide" && state.view.slide === si;
          return "<li><button type=\"button\" data-go=\"" + ui + ":" + si + "\" class=\"lesson" +
            (active ? " active" : "") + (state.seen[u.id][si] ? " seen" : "") + "\"" +
            (active ? " aria-current=\"step\"" : "") + "><span class=\"dot\" aria-hidden=\"true\"></span>" +
            "<span>" + esc(s.title) + "</span></button></li>";
        }).join("") +
          "<li><button type=\"button\" data-go=\"" + ui + ":quiz\" class=\"lesson quiz-link" +
          (state.view.mode === "quiz" ? " active" : "") + (q && q.tries ? " seen" : "") + "\">" +
          icon("quiz") + "<span>Evaluación" + (q && q.tries ? " · " + q.best + " %" : "") + "</span></button></li></ol>";
      }
      return "<li class=\"unit" + (current ? " current" : "") + (done ? " done" : "") + "\">" +
        "<button type=\"button\" class=\"unit-btn\" data-go=\"" + ui + ":0\"" + (current ? " aria-expanded=\"true\"" : " aria-expanded=\"false\"") + ">" +
        icon(u.icon, "unit-icon") + "<span class=\"unit-text\"><span class=\"unit-label\">" + esc(u.label) +
        " · " + u.minutes + " min</span><span class=\"unit-title\">" + esc(u.title) + "</span></span>" + status +
        "</button>" + inner + "</li>";
    }).join("");
    els.unitList.innerHTML = html;
    els.summaryLink.classList.toggle("active", state.view.mode === "summary");
  }

  function header(unit, kicker) {
    els.kicker.textContent = kicker;
    els.unitTitle.textContent = unit ? unit.title : "Tu progreso en el curso";
  }

  function renderSlide() {
    var u = units[state.view.unit];
    var s = u.slides[state.view.slide];
    state.seen[u.id][state.view.slide] = true;
    header(u, u.label + " · Lección " + (state.view.slide + 1) + " de " + u.slides.length);
    var media = s.image ? figure(s.image.src, s.image.alt, s.image.caption, true) : "";
    els.stage.innerHTML =
      "<article class=\"slide" + (s.image ? "" : " no-media") + "\">" +
      "<h2 class=\"slide-title\" tabindex=\"-1\">" + esc(s.title) + "</h2>" +
      media + "<div class=\"prose\">" + s.body.map(block).join("") + "</div></article>";
    setFooter(state.view.slide + 1 + " / " + u.slides.length,
      !(state.view.unit === 0 && state.view.slide === 0),
      state.view.slide === u.slides.length - 1 ? "Ir a la evaluación" : "Siguiente", "primary");
  }

  // ----------------------------------------------------------------- quiz
  function seededOrder(n, seed) {
    var order = [];
    for (var i = 0; i < n; i++) order.push(i);
    var x = seed * 9301 + 49297;
    for (var j = n - 1; j > 0; j--) {
      x = (x * 9301 + 49297) % 233280;
      var k = Math.floor((x / 233280) * (j + 1));
      var t = order[j]; order[j] = order[k]; order[k] = t;
    }
    return order;
  }

  function startQuiz(ui) {
    var u = units[ui];
    var tries = (state.quiz[u.id] && state.quiz[u.id].tries) || 0;
    quizRun = {
      unit: ui, submitted: false,
      answers: u.quiz.questions.map(function () { return null; }),
      orders: u.quiz.questions.map(function (q, qi) { return seededOrder(q.options.length, (tries + 1) * 31 + qi * 7 + ui); })
    };
  }

  function renderQuiz() {
    var ui = state.view.unit, u = units[ui];
    var q = state.quiz[u.id];
    var pass = passingScore();
    header(u, u.label + " · Evaluación");
    if (!quizRun || quizRun.unit !== ui) quizRun = null;

    if (!quizRun) {
      var unseen = state.seen[u.id].filter(function (b) { return !b; }).length;
      els.stage.innerHTML = "<article class=\"quiz-intro\">" +
        "<h2 class=\"slide-title\" tabindex=\"-1\">Evaluación: " + esc(u.title) + "</h2>" +
        "<p>" + u.quiz.questions.length + " preguntas de selección única. Necesitas <strong>" + pass +
        " %</strong> o más para aprobar la unidad. Puedes repetirla: se guarda tu mejor nota.</p>" +
        (q && q.tries ? "<p class=\"best " + (q.best >= pass ? "ok" : "ko") + "\">" + icon(q.best >= pass ? "check" : "note") +
          "Tu mejor nota: <strong>" + q.best + " %</strong> en " + q.tries + (q.tries === 1 ? " intento" : " intentos") + ".</p>" : "") +
        (unseen ? "<aside class=\"callout note\">" + icon("note") + "<div>Te " + (unseen === 1 ? "falta 1 lección" : "faltan " + unseen + " lecciones") +
          " de esta unidad. Te recomendamos verlas antes de presentar la evaluación.</div></aside>" : "") +
        "<button type=\"button\" class=\"btn primary big\" id=\"quiz-start\">" + icon("quiz") +
        (q && q.tries ? "Presentar de nuevo" : "Comenzar evaluación") + "</button></article>";
      $("quiz-start").addEventListener("click", function () { startQuiz(ui); render(true); });
      setFooter("Evaluación", true, nextLabelAfterQuiz(ui), q && q.best >= pass ? "primary" : "ghost");
      return;
    }

    var run = quizRun;
    var correct = 0;
    var qs = u.quiz.questions.map(function (qq, qi) {
      var chosen = run.answers[qi];
      var isRight = chosen === qq.answer;
      if (run.submitted && isRight) correct++;
      var opts = run.orders[qi].map(function (oi, pos) {
        var cls = "option";
        if (run.submitted) {
          if (oi === qq.answer) cls += " right";
          else if (oi === chosen) cls += " wrong";
        }
        return "<label class=\"" + cls + "\"><input type=\"radio\" name=\"q" + qi + "\" value=\"" + oi + "\"" +
          (chosen === oi ? " checked" : "") + (run.submitted ? " disabled" : "") + ">" +
          "<span class=\"letter\">" + "ABCD".charAt(pos) + "</span><span class=\"opt-text\">" + md(qq.options[oi]) + "</span></label>";
      }).join("");
      return "<fieldset class=\"question" + (run.submitted ? (isRight ? " is-right" : " is-wrong") : "") + "\">" +
        "<legend><span class=\"qnum\">Pregunta " + (qi + 1) + " de " + u.quiz.questions.length + "</span>" + md(qq.q) + "</legend>" +
        (qq.image ? figure(qq.image, "Imagen de apoyo para la pregunta " + (qi + 1), "", false, "inline") : "") +
        "<div class=\"options\">" + opts + "</div>" +
        (run.submitted ? "<p class=\"feedback\">" + icon(isRight ? "check" : "note") + "<span><strong>" +
          (isRight ? "¡Correcto! " : "Respuesta correcta: " + md(qq.options[qq.answer]) + ". ") + "</strong>" + md(qq.explain) + "</span></p>" : "") +
        "</fieldset>";
    }).join("");

    var result = "";
    if (run.submitted) {
      var pct = Math.round(100 * correct / u.quiz.questions.length);
      var ok = pct >= pass;
      result = "<div class=\"result " + (ok ? "ok" : "ko") + "\" role=\"status\">" + icon(ok ? "trophy" : "note") +
        "<div><strong>" + (ok ? "¡Aprobaste!" : "Aún no alcanzas el " + pass + " %") + "</strong>" +
        "<span>Obtuviste " + correct + " de " + u.quiz.questions.length + " (" + pct + " %). " +
        (ok ? "Puedes seguir con la siguiente unidad." : "Repasa las lecciones marcadas y vuelve a intentarlo.") + "</span></div>" +
        "<button type=\"button\" class=\"btn ghost\" id=\"quiz-retry\">Repetir evaluación</button></div>";
    }
    var answered = run.answers.filter(function (a) { return a !== null; }).length;
    els.stage.innerHTML = "<article class=\"quiz\"><h2 class=\"slide-title\" tabindex=\"-1\">Evaluación: " + esc(u.title) + "</h2>" +
      result + "<form id=\"quiz-form\" novalidate>" + qs +
      (run.submitted ? "" : "<div class=\"quiz-actions\"><span id=\"quiz-count\">" + answered + " de " + u.quiz.questions.length +
        " respondidas</span><button type=\"submit\" class=\"btn primary big\" id=\"quiz-submit\"" +
        (answered < u.quiz.questions.length ? " disabled" : "") + ">Enviar respuestas</button></div>") +
      "</form></article>";

    var form = $("quiz-form");
    form.addEventListener("change", function (e) {
      if (e.target.name && e.target.name.charAt(0) === "q") {
        run.answers[parseInt(e.target.name.slice(1), 10)] = parseInt(e.target.value, 10);
        var n = run.answers.filter(function (a) { return a !== null; }).length;
        $("quiz-count").textContent = n + " de " + u.quiz.questions.length + " respondidas";
        $("quiz-submit").disabled = n < u.quiz.questions.length;
      }
    });
    form.addEventListener("submit", function (e) {
      e.preventDefault();
      if (run.answers.some(function (a) { return a === null; })) return;
      submitQuiz(ui);
    });
    if ($("quiz-retry")) $("quiz-retry").addEventListener("click", function () { startQuiz(ui); render(true); });
    setFooter("Evaluación", true, nextLabelAfterQuiz(ui), run.submitted ? "primary" : "ghost");
  }

  function submitQuiz(ui) {
    var u = units[ui], run = quizRun;
    var correct = 0;
    u.quiz.questions.forEach(function (qq, qi) {
      var ok = run.answers[qi] === qq.answer;
      if (ok) correct++;
      SCORM.recordInteraction(u.id + "-p" + (qi + 1), "abcd".charAt(run.answers[qi]), "abcd".charAt(qq.answer), ok);
    });
    var pct = Math.round(100 * correct / u.quiz.questions.length);
    var prev = state.quiz[u.id] || { best: 0, tries: 0 };
    state.quiz[u.id] = { best: Math.max(prev.best, pct), tries: prev.tries + 1 };
    run.submitted = true;
    saveProgress();
    render(true);
    window.scrollTo(0, 0);
    els.main.scrollTop = 0;
  }

  function nextLabelAfterQuiz(ui) {
    return ui === units.length - 1 ? "Ver mi resultado" : "Siguiente unidad";
  }

  // --------------------------------------------------------------- summary
  function renderSummary() {
    var st = stats(), pass = passingScore();
    var name = SCORM.studentName();
    header(null, "Resumen del curso");
    var rows = units.map(function (u, ui) {
      var q = state.quiz[u.id];
      var seen = state.seen[u.id].filter(Boolean).length;
      var score = q && q.tries ? q.best + " %" : "Pendiente";
      var cls = q && q.tries ? (q.best >= pass ? "ok" : "ko") : "pending";
      return "<tr><th scope=\"row\"><button type=\"button\" class=\"link\" data-go=\"" + ui + ":0\">" + esc(u.label) + ". " + esc(u.title) + "</button></th>" +
        "<td>" + seen + " / " + u.slides.length + "</td><td><span class=\"pill " + cls + "\">" + score + "</span></td></tr>";
    }).join("");
    var message;
    if (st.passed) message = "<div class=\"result ok big\">" + icon("trophy") + "<div><strong>¡Felicitaciones" + (name ? ", " + esc(name) : "") +
      "! Aprobaste el curso.</strong><span>Tu nota final es " + st.average + " / 100. Don Juan ya puede dejar la libreta.</span></div></div>";
    else if (st.complete) message = "<div class=\"result ko big\">" + icon("note") + "<div><strong>Ya presentaste todas las evaluaciones.</strong>" +
      "<span>Tu promedio es " + st.average + " %. Necesitas " + pass + " % para aprobar: repite las evaluaciones con nota más baja.</span></div></div>";
    else message = "<div class=\"result neutral big\">" + icon("progress") + "<div><strong>" + (name ? "¡Hola, " + esc(name) + "! " : "") +
      "Vas en el " + st.percent + " % del curso.</strong><span>Para terminar, recorre todas las lecciones (" + st.seenSlides + " de " + st.totalSlides +
      " vistas) y presenta las " + units.length + " evaluaciones (" + st.attempted + " presentadas).</span></div></div>";

    els.stage.innerHTML = "<article class=\"summary\"><h2 class=\"slide-title\" tabindex=\"-1\">Mi progreso</h2>" + message +
      "<div class=\"table-wrap\"><table class=\"summary-table\"><thead><tr><th scope=\"col\">Unidad</th><th scope=\"col\">Lecciones vistas</th>" +
      "<th scope=\"col\">Mejor nota</th></tr></thead><tbody>" + rows + "</tbody></table></div>" +
      certificateCard(st) +
      "<p class=\"fine\">La nota final es el promedio de las mejores notas de las " + units.length +
      " evaluaciones. Se aprueba con " + pass + " % o más y todas las lecciones vistas.</p>" +
      (SCORM.isLMS ? "<button type=\"button\" class=\"btn primary\" id=\"finish\">" + icon("check") + "Guardar y salir del curso</button>" :
        "<aside class=\"callout note\">" + icon("note") + "<div><strong class=\"callout-title\">Modo vista previa</strong>" +
        "Estás viendo el curso fuera del campus: tu progreso se guarda solo en este navegador.</div></aside>" +
        "<button type=\"button\" class=\"btn ghost\" id=\"reset\">Borrar mi progreso de prueba</button>") +
      "</article>";
    if ($("cert-download")) $("cert-download").addEventListener("click", downloadCertificate);
    if ($("finish")) $("finish").addEventListener("click", function () {
      saveProgress();
      SCORM.finish(stats().complete);
      els.stage.innerHTML = "<article class=\"summary\"><h2 class=\"slide-title\" tabindex=\"-1\">¡Progreso guardado!</h2>" +
        "<p>Ya puedes cerrar esta ventana o volver al campus.</p></article>";
      els.footer.hidden = true;
    });
    if ($("reset")) $("reset").addEventListener("click", function () {
      SCORM.resetLocal();
      window.location.reload();
    });
    setFooter("", true, "", "none");
  }

  // ----------------------------------------------------------- certificate
  // The PDF is generated in the browser. What makes it verifiable is the
  // record written to the LMS when it is issued (cmi.comments):
  //   OSAICERT|1|<serial>|<YYYY-MM-DD>|<grade>|<P|N>|<sha256>|<md5>;
  // The campus page local/certverify looks the serial up in Moodle's SCORM
  // tracking data and compares the hashes of an uploaded PDF.
  // The serial and date are kept in suspend_data, so downloading again gives a
  // byte-identical file (same hashes). A new serial is issued only when the
  // grade or the name changes.
  var CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

  function newSerial(prefix) {
    var bytes = new Uint8Array(12), s = "";
    var cryptoObj = window.crypto || window.msCrypto;
    if (cryptoObj && cryptoObj.getRandomValues) cryptoObj.getRandomValues(bytes);
    else for (var i = 0; i < bytes.length; i++) bytes[i] = Math.floor(Math.random() * 256);
    for (var j = 0; j < bytes.length; j++) s += CROCKFORD.charAt(bytes[j] & 31);
    return prefix + "-" + s.slice(0, 4) + "-" + s.slice(4, 8) + "-" + s.slice(8, 12);
  }

  function formatIsoDate(iso) {
    var p = iso.split("-");
    return new Date(+p[0], +p[1] - 1, +p[2], 12).toLocaleDateString("es-CO", { day: "numeric", month: "long", year: "numeric" });
  }

  function verifyUrl(serial) {
    return COURSE.certificate.verifyUrl.replace("{serial}", encodeURIComponent(serial));
  }

  function certificateCard(st) {
    var cert = COURSE.certificate;
    if (!cert || !window.Certificate) return "";
    if (!st.complete) {
      return "<aside class=\"cert-card locked\">" + icon("trophy") + "<div><strong>" + esc(cert.title) + "</strong>" +
        "<span>Podrás descargarlo cuando veas todas las lecciones y presentes las " + units.length +
        " evaluaciones. Incluirá tu nombre, las competencias trabajadas, tu nota final y un código QR de verificación.</span></div></aside>";
    }
    var name = SCORM.studentFullName();
    var issued = state.cert && state.cert.grade === st.average ? state.cert : null;
    return "<aside class=\"cert-card\">" + icon("trophy") + "<div><strong>" + esc(cert.title) + "</strong>" +
      "<span>Un PDF con tu nombre, las competencias trabajadas en cada unidad, tu nota final (" + st.average +
      "/100) y un código QR para verificarlo en " + esc(cert.site) + ".</span>" +
      (name ? "<span class=\"cert-name\">A nombre de: <b>" + esc(name) + "</b></span>" :
        "<label class=\"cert-input\">Nombre completo para el certificado" +
        (SCORM.isLMS ? "" : " <em>(vista previa: en el campus se usa el nombre de tu cuenta)</em>") +
        "<input id=\"cert-name\" type=\"text\" autocomplete=\"name\" maxlength=\"80\"" +
        (issued ? " value=\"" + esc(issued.name) + "\"" : "") + "></label>") +
      "<button type=\"button\" class=\"btn primary\" id=\"cert-download\">" + icon("download") +
      "Descargar certificado (PDF)</button>" +
      "<span id=\"cert-msg\" class=\"cert-msg\" role=\"status\"></span>" +
      "<span id=\"cert-info\" class=\"cert-info\">" + (issued ? certInfo(issued) : "") + "</span></div></aside>";
  }

  function certRecord(c) {
    return ["OSAICERT", 1, c.serial, c.issued, c.grade, c.passed ? "P" : "N", c.sha256, c.md5].join("|") + ";";
  }

  // The campus reads cmi.comments to verify certificates. Moodle appends to it
  // in memory, so a stale browser tab can overwrite it: at each session start,
  // write back any issued certificate that is missing from the record.
  function healCertRecords() {
    if (!SCORM.isLMS) return;
    var current = SCORM.get("cmi.comments"), missing = "";
    [state.cert].concat(state.certHistory).forEach(function (c) {
      if (c && c.serial && c.sha256 && current.indexOf(c.serial) < 0) missing += certRecord(c);
    });
    if (missing) {
      // Moodle appends whatever is set to cmi.comments; other LMSs replace it.
      SCORM.set("cmi.comments", SCORM.appendsComments() ? missing : current + missing);
      SCORM.commit();
    }
  }

  function certInfo(c) {
    return "Serial <b>" + esc(c.serial) + "</b> · expedido el " + esc(formatIsoDate(c.issued)) +
      " · SHA-256 <code>" + esc(c.sha256.slice(0, 16)) + "…</code> · <a href=\"" + esc(verifyUrl(c.serial)) +
      "\" target=\"_blank\" rel=\"noopener\">Verificar en el campus</a>";
  }

  function downloadCertificate() {
    var cert = COURSE.certificate, st = stats();
    var name = SCORM.studentFullName() || (($("cert-name") || {}).value || "").trim();
    if (!name) {
      $("cert-msg").textContent = "Escribe tu nombre completo para generar el certificado.";
      if ($("cert-name")) $("cert-name").focus();
      return;
    }
    var c = state.cert;
    var isNew = !(c && c.grade === st.average && c.name === name);
    if (isNew) {
      var d = new Date();
      c = {
        serial: newSerial(cert.serialPrefix), name: name, grade: st.average, passed: st.passed,
        issued: d.getFullYear() + "-" + ("0" + (d.getMonth() + 1)).slice(-2) + "-" + ("0" + d.getDate()).slice(-2)
      };
    }
    var hours = Math.round(units.reduce(function (t, u) { return t + u.minutes; }, 0) / 60);
    var data = {
      name: name, title: cert.title, program: cert.program, courseLine: cert.courseLine,
      issuer: cert.issuer, site: cert.site, courseTitle: COURSE.title, hours: hours,
      grade: c.grade, passed: c.passed, date: formatIsoDate(c.issued),
      serial: c.serial, verifyUrl: verifyUrl(c.serial),
      logo: window.CERT_ASSETS && window.CERT_ASSETS.logo,
      units: units.map(function (u) {
        var q = state.quiz[u.id];
        return { label: u.label, title: u.title, skills: u.skills || [], score: q && q.tries ? q.best : null };
      })
    };
    var bytes = window.Certificate.toBytes(window.Certificate.build(data));
    c.sha256 = window.Hash.sha256(bytes);
    c.md5 = window.Hash.md5(bytes);
    if (isNew) {
      if (state.cert) {
        var prev = state.cert;
        state.certHistory.unshift({ serial: prev.serial, issued: prev.issued, grade: prev.grade,
          passed: prev.passed, sha256: prev.sha256, md5: prev.md5 });
        state.certHistory = state.certHistory.slice(0, 10);
      }
      state.cert = c;
      SCORM.set("cmi.comments", certRecord(c));
      saveProgress();
    }
    var safe = name.normalize ? name.normalize("NFD").replace(/[\u0300-\u036f]/g, "") : name;
    safe = safe.replace(/[^A-Za-z0-9]+/g, "_").replace(/^_|_$/g, "");
    window.Certificate.save(bytes, "Certificado_" + c.serial + "_" + safe + ".pdf");
    $("cert-msg").textContent = "Listo: revisa tus descargas.";
    $("cert-info").innerHTML = certInfo(c);
  }

  // ------------------------------------------------------------ navigation
  function setFooter(counter, canPrev, nextLabel, nextStyle) {
    els.counter.textContent = counter;
    els.prev.disabled = !canPrev;
    els.next.hidden = nextStyle === "none";
    els.next.className = "btn " + (nextStyle === "ghost" ? "ghost" : "primary");
    els.nextLabel.textContent = nextLabel;
  }

  function go(target) {
    if (target.mode === "quiz" && !(quizRun && quizRun.unit === target.unit && !quizRun.submitted)) quizRun = null;
    state.view = target;
    closeDrawer();
    render(true);
  }

  function next() {
    var v = state.view, u = units[v.unit];
    if (v.mode === "slide") {
      if (v.slide < u.slides.length - 1) go({ unit: v.unit, slide: v.slide + 1, mode: "slide" });
      else go({ unit: v.unit, slide: 0, mode: "quiz" });
    } else if (v.mode === "quiz") {
      if (v.unit < units.length - 1) go({ unit: v.unit + 1, slide: 0, mode: "slide" });
      else go({ unit: v.unit, slide: 0, mode: "summary" });
    }
  }

  function prev() {
    var v = state.view;
    if (v.mode === "summary") go({ unit: units.length - 1, slide: 0, mode: "quiz" });
    else if (v.mode === "quiz") go({ unit: v.unit, slide: units[v.unit].slides.length - 1, mode: "slide" });
    else if (v.slide > 0) go({ unit: v.unit, slide: v.slide - 1, mode: "slide" });
    else if (v.unit > 0) go({ unit: v.unit - 1, slide: 0, mode: "quiz" });
  }

  function render(moveFocus) {
    els.footer.hidden = false;
    if (state.view.mode === "slide") renderSlide();
    else if (state.view.mode === "quiz") renderQuiz();
    else renderSummary();
    renderNav();
    saveProgress();
    els.main.scrollTop = 0;
    if (window.scrollY) window.scrollTo(0, 0); // mobile: the page itself scrolls
    if (moveFocus) {
      var h = els.stage.querySelector(".slide-title");
      if (h) h.focus({ preventScroll: true });
    }
  }

  // --------------------------------------------------------------- drawer
  function openDrawer() {
    document.body.classList.add("drawer-open");
    els.menuBtn.setAttribute("aria-expanded", "true");
  }
  function closeDrawer() {
    document.body.classList.remove("drawer-open");
    els.menuBtn.setAttribute("aria-expanded", "false");
  }

  // -------------------------------------------------------------- lightbox
  function openZoom(src, alt) {
    var meta = IMAGES[src];
    if (!meta) return;
    var w = meta.widths[meta.widths.length - 1];
    els.zoomImg.src = "multimedia/img/" + src + "-" + w + "." + meta.ext;
    els.zoomImg.alt = alt;
    if (els.zoom.showModal) els.zoom.showModal(); else els.zoom.setAttribute("open", "");
  }
  function closeZoom() {
    if (els.zoom.close) els.zoom.close(); else els.zoom.removeAttribute("open");
  }

  // ------------------------------------------------------------------ boot
  function boot() {
    ["stage", "kicker", "unitTitle", "counter", "prev", "next", "nextLabel", "unitList", "progressBar",
     "progressText", "scoreText", "scoreNote", "mobileProgress", "menuBtn", "summaryLink", "footer", "main",
     "zoom", "zoomImg", "zoomClose", "previewBadge", "scrim"].forEach(function (id) { els[id] = $(id); });

    SCORM.init();
    restore(SCORM.get("cmi.suspend_data"));
    restoreLocation(SCORM.get("cmi.core.lesson_location"));
    healCertRecords();
    els.previewBadge.hidden = SCORM.isLMS;
    document.title = COURSE.title;

    els.next.addEventListener("click", next);
    els.prev.addEventListener("click", prev);
    els.menuBtn.addEventListener("click", function () {
      document.body.classList.contains("drawer-open") ? closeDrawer() : openDrawer();
    });
    els.scrim.addEventListener("click", closeDrawer);
    els.summaryLink.addEventListener("click", function () { go({ unit: units.length - 1, slide: 0, mode: "summary" }); });

    document.addEventListener("click", function (e) {
      var t = e.target.closest ? e.target.closest("[data-go],[data-zoom],[data-copy]") : null;
      if (!t) return;
      if (t.hasAttribute("data-go")) {
        var p = t.getAttribute("data-go").split(":");
        var ui = parseInt(p[0], 10);
        if (p[1] === "quiz") go({ unit: ui, slide: 0, mode: "quiz" });
        else go({ unit: ui, slide: parseInt(p[1], 10), mode: "slide" });
      } else if (t.hasAttribute("data-zoom")) {
        openZoom(t.getAttribute("data-zoom"), t.getAttribute("data-alt"));
      } else if (t.hasAttribute("data-copy")) {
        var text = t.getAttribute("data-copy");
        var label = t.querySelector("span");
        var done = function () { label.textContent = "¡Copiado!"; setTimeout(function () { label.textContent = "Copiar"; }, 1600); };
        if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(text).then(done, function () {});
      }
    });

    els.zoomClose.addEventListener("click", closeZoom);
    els.zoom.addEventListener("click", function (e) { if (e.target === els.zoom) closeZoom(); });

    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape") { closeDrawer(); return; }
      var tag = (e.target.tagName || "").toLowerCase();
      if (tag === "input" || tag === "textarea" || tag === "select" || (els.zoom.open)) return;
      if (e.altKey || e.ctrlKey || e.metaKey) return;
      if (e.key === "ArrowRight" && state.view.mode === "slide") { e.preventDefault(); next(); }
      if (e.key === "ArrowLeft" && state.view.mode === "slide") { e.preventDefault(); prev(); }
    });

    // Desktop layout: only .main and the sidebar scroll. If anything ever scrolls
    // the page itself (e.g. focus moving to an element outside the view), put it
    // back so the course never slides out of the LMS frame.
    var desktop = window.matchMedia("(min-width: 901px)");
    window.addEventListener("scroll", function () {
      if (desktop.matches && (window.scrollY || window.scrollX)) window.scrollTo(0, 0);
    });

    var leave = function () { saveProgress(); SCORM.finish(stats().complete); };
    window.addEventListener("pagehide", leave);
    window.addEventListener("beforeunload", leave);

    render(false);
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
  else boot();
})();
